# Generated by Django 6.0.1 on 2026-01-27 00:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0002_alter_company_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fabric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(max_length=50)),
                ('fabric_class', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=100)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=6)),
                ('country_of_origin', models.CharField(max_length=50)),
                ('open_or_tubular', models.CharField(choices=[('open', 'Open'), ('tubular', 'Tubular')])),
                ('yarn_type', models.CharField(blank=True, max_length=50, null=True)),
                ('yarn_size', models.CharField(blank=True, max_length=50, null=True)),
                ('cuttable', models.IntegerField()),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.vendor')),
            ],
        ),
    ]
