# Generated by Django 6.0.1 on 2026-01-27 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabrics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fabric',
            name='vendor_code',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fabric',
            name='item_code',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
