# Generated by Django 6.0.1 on 2026-02-12 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabrics', '0002_fabric_vendor_code_alter_fabric_item_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='fabric',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
