# Generated by Django 6.0.1 on 2026-02-19 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabrics', '0004_fabriccolor'),
    ]

    operations = [
        migrations.AddField(
            model_name='fabriccolor',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
