# Generated by Django 6.0.1 on 2026-02-19 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabrics', '0005_fabriccolor_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fabriccolor',
            name='lab_dip',
            field=models.CharField(blank=True, default='', max_length=20),
            preserve_default=False,
        ),
    ]
