# Generated by Django 6.0.1 on 2026-02-19 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colors', '0005_delete_fabriccolor'),
        ('fabrics', '0006_alter_fabriccolor_lab_dip'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='fabriccolor',
            constraint=models.UniqueConstraint(fields=('fabric', 'color'), name='unique_fabric_color'),
        ),
    ]
