# Generated by Django 6.0.1 on 2026-02-20 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colors', '0005_delete_fabriccolor'),
        ('fabrics', '0007_fabriccolor_unique_fabric_color'),
    ]

    operations = [
        migrations.AlterConstraint(
            model_name='fabriccolor',
            name='unique_fabric_color',
            constraint=models.UniqueConstraint(fields=('fabric', 'color'), name='unique_fabric_color', violation_error_message='This fabric & color is already registered.'),
        ),
    ]
