# Generated by Django 6.0.1 on 2026-03-16 20:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fabrics', '0008_alter_fabriccolor_unique_fabric_color'),
        ('pos', '0006_alter_purchaseorder_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(max_length=30, unique=True)),
                ('received_date', models.DateField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_receipts', to=settings.AUTH_USER_MODEL)),
                ('purchase_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='pos.purchaseorder')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryReceiptLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_yards', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('received_yards', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tolerance_percent', models.DecimalField(decimal_places=2, default=5, max_digits=5)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('OK', 'Ok'), ('UNDER', 'Under'), ('OVER', 'Over')], default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fabric', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fabrics.fabriccolor')),
                ('po_fabric', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipt_lines', to='pos.purchaseorderfabrics')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.inventoryreceipt')),
            ],
        ),
    ]
