# Generated by Django 6.0.1 on 2026-02-26 03:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0003_company_is_active'),
        ('garments', '0005_alter_garmentstyle_fabrics'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.CharField(max_length=50)),
                ('order_number', models.CharField(max_length=50)),
                ('po_ship_date', models.DateField()),
                ('total_pieces', models.IntegerField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.customer')),
                ('style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garments.garmentstyle')),
            ],
        ),
    ]
