# Generated by Django 6.0.1 on 2026-02-26 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demand', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='demand',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
