# Generated by Django 6.0.1 on 2026-02-26 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demand', '0002_demand_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demand',
            name='total_pieces',
            field=models.PositiveIntegerField(),
        ),
    ]
