# Generated by Django 6.0.1 on 2026-02-26 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demand', '0003_alter_demand_total_pieces'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demand',
            name='job',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='demand',
            name='order_number',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
