# Generated by Django 6.0.1 on 2026-01-25 06:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='color',
            name='created_by',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
