# Generated by Django 6.0.1 on 2026-02-17 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colors', '0002_color_created_at_color_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
