# Generated by Django 6.0.1 on 2026-02-19 01:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colors', '0003_color_is_active'),
        ('fabrics', '0003_fabric_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='FabricColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_dip', models.CharField(blank=True, max_length=20, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colors.color')),
                ('fabric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fabrics.fabric')),
            ],
        ),
    ]
