# Generated by Django 6.0.1 on 2026-02-19 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colors', '0004_fabriccolor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FabricColor',
        ),
    ]
