# Generated by Django 6.0.1 on 2026-03-02 03:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0003_company_is_active'),
        ('demand', '0004_alter_demand_job_alter_demand_order_number'),
        ('fabrics', '0008_alter_fabriccolor_unique_fabric_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_number', models.CharField(max_length=20, unique=True)),
                ('order_date', models.DateField(default=django.utils.timezone.now)),
                ('expected_delivery', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('APPROVED', 'Approved'), ('RECEIVED', 'Received')], default='OPEN', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('demand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='demand.demand')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='companies.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrderFabrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yards', models.PositiveIntegerField()),
                ('fabric', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fabrics.fabriccolor')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fabrics', to='pos.purchaseorder')),
            ],
        ),
    ]
