# Generated by Django 6.0.1 on 2026-03-05 05:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demand', '0004_alter_demand_job_alter_demand_order_number'),
        ('fabrics', '0008_alter_fabriccolor_unique_fabric_color'),
        ('pos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderfabrics',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='demand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders', to='demand.demand'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorderfabrics',
            constraint=models.UniqueConstraint(fields=('purchase_order', 'fabric'), name='unique_purchase_order_fabric'),
        ),
    ]
