# Generated by Django 6.0.1 on 2026-03-05 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0002_purchaseorderfabrics_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorderfabrics',
            name='is_active',
        ),
    ]
