# Generated by Django 6.0.1 on 2026-03-10 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0004_alter_purchaseorder_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('OPEN', 'OPEN'), ('APPROVED', 'APPROVED'), ('RECEIVED', 'RECEIVED'), ('CLOSED', 'CLOSED')], default='OPEN', max_length=20),
        ),
    ]
