# Generated by Django 6.0.1 on 2026-02-20 04:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fabrics', '0008_alter_fabriccolor_unique_fabric_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='GarmentStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GarmentStyleFabricColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fabric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fabrics.fabriccolor')),
                ('garment_style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garments.garmentstyle')),
            ],
            options={
                'unique_together': {('garment_style', 'fabric')},
            },
        ),
        migrations.AddField(
            model_name='garmentstyle',
            name='fabrics',
            field=models.ManyToManyField(through='garments.GarmentStyleFabricColor', to='fabrics.fabriccolor'),
        ),
    ]
