# Generated by Django 6.0.1 on 2026-02-20 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fabrics', '0008_alter_fabriccolor_unique_fabric_color'),
        ('garments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='garmentstylefabriccolor',
            old_name='fabric',
            new_name='fabriccolor',
        ),
        migrations.AlterUniqueTogether(
            name='garmentstylefabriccolor',
            unique_together={('garment_style', 'fabriccolor')},
        ),
    ]
