# Generated by Django 6.0.1 on 2026-02-23 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garments', '0002_rename_fabric_garmentstylefabriccolor_fabriccolor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='garmentstyle',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
