# Generated by Django 6.0.1 on 2026-02-24 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabrics', '0008_alter_fabriccolor_unique_fabric_color'),
        ('garments', '0003_garmentstyle_is_active'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='garmentstylefabriccolor',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='garmentstylefabriccolor',
            constraint=models.UniqueConstraint(fields=('garment_style', 'fabriccolor'), name='unique_garment_style_fabriccolor'),
        ),
    ]
