# Generated by Django 6.0.1 on 2026-02-25 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabrics', '0008_alter_fabriccolor_unique_fabric_color'),
        ('garments', '0004_alter_garmentstylefabriccolor_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garmentstyle',
            name='fabrics',
            field=models.ManyToManyField(blank=True, through='garments.GarmentStyleFabricColor', to='fabrics.fabriccolor'),
        ),
    ]
